# This file is auto-generated by scripts/render_homebrew_formula.py and
# refreshed on every release by .github/workflows/homebrew-formula.yml.
# Do not edit by hand — changes will be overwritten on the next release.
class Kymostudio < Formula
  desc "Render SVG diagrams to PNG and PDF (pure-Rust, no system deps)"
  homepage "https://github.com/kymostudio/kymostudio"
  version "0.4.7"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/kymostudio/kymostudio/releases/download/v0.4.7/kymostudio-aarch64-apple-darwin.tar.xz"
      sha256 "4bd8d1015916550a65c1fba3a33e82ff30f3913b9af7762945efeea6a6754782"
    end
    on_intel do
      url "https://github.com/kymostudio/kymostudio/releases/download/v0.4.7/kymostudio-x86_64-apple-darwin.tar.xz"
      sha256 "bbb3d4d6342cb184032f3cac49ca6ca41983c5a8c43c5237cb6db4328b6f925e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kymostudio/kymostudio/releases/download/v0.4.7/kymostudio-aarch64-unknown-linux-gnu.tar.xz"
      sha256 "3bd28365eae9e6fe682b74b4c73653156c800983d7750c2ff1cd1124034076e8"
    end
    on_intel do
      url "https://github.com/kymostudio/kymostudio/releases/download/v0.4.7/kymostudio-x86_64-unknown-linux-gnu.tar.xz"
      sha256 "e40f7d345f5c8d7bec8d915a7a0849ce97315261f8bc4e4493fb445192e632dc"
    end
  end

  # The CLI binary is `kymo` (install-name `kymostudio`, like pip/npm/cargo).
  def install
    bin.install "kymo"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/kymo --version")
  end
end
