# This file is auto-generated by scripts/render_homebrew_formula.py and
# refreshed on every release by .github/workflows/homebrew-formula.yml.
# Do not edit by hand — changes will be overwritten on the next release.
class Kymostudio < Formula
  desc "Render SVG diagrams to PNG and PDF (pure-Rust, no system deps)"
  homepage "https://github.com/kymostudio/kymostudio"
  version "0.4.10"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/kymostudio/kymostudio/releases/download/v0.4.10/kymostudio-aarch64-apple-darwin.tar.xz"
      sha256 "a2602e2c6d14c47cb548ac29cbe624148e5b27f0a52b81c4a09b66985e950b54"
    end
    on_intel do
      url "https://github.com/kymostudio/kymostudio/releases/download/v0.4.10/kymostudio-x86_64-apple-darwin.tar.xz"
      sha256 "617de783b8340a11cd674cb5cd32cbd881305c60c4de8df724775ec840f31f7a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kymostudio/kymostudio/releases/download/v0.4.10/kymostudio-aarch64-unknown-linux-gnu.tar.xz"
      sha256 "2347f298ce38f163523416fb16b2656081de75e1077d05b9228fe9a83dd52195"
    end
    on_intel do
      url "https://github.com/kymostudio/kymostudio/releases/download/v0.4.10/kymostudio-x86_64-unknown-linux-gnu.tar.xz"
      sha256 "2a81b5598ff151d535db15bf32ac024bf4b065861f9136987a13ffa245d80cf1"
    end
  end

  # The CLI binary is `kymo` (install-name `kymostudio`, like pip/npm/cargo).
  def install
    bin.install "kymo"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/kymo --version")
  end
end
