# This file is auto-generated by scripts/render_homebrew_formula.py and
# refreshed on every release by .github/workflows/homebrew-formula.yml.
# Do not edit by hand — changes will be overwritten on the next release.
class Kymostudio < Formula
  desc "Render SVG diagrams to PNG and PDF (pure-Rust, no system deps)"
  homepage "https://github.com/kymostudio/kymostudio"
  version "0.4.8"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/kymostudio/kymostudio/releases/download/v0.4.8/kymostudio-aarch64-apple-darwin.tar.xz"
      sha256 "cef8f3b54382daecc6f848996486b8294f1ebc3cc7f2ed2d894818f5bece6d9e"
    end
    on_intel do
      url "https://github.com/kymostudio/kymostudio/releases/download/v0.4.8/kymostudio-x86_64-apple-darwin.tar.xz"
      sha256 "3264b02dbcbe3fd8f4967cdc3b4a86531be0f7648c96402bd592eafa068a4009"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kymostudio/kymostudio/releases/download/v0.4.8/kymostudio-aarch64-unknown-linux-gnu.tar.xz"
      sha256 "e03ba5ea643d35b125c147cdb0cb5657bb86d489219b748a7286d01475e918e1"
    end
    on_intel do
      url "https://github.com/kymostudio/kymostudio/releases/download/v0.4.8/kymostudio-x86_64-unknown-linux-gnu.tar.xz"
      sha256 "355b2531296eb773319110eb24baa87e8c105a366c178f8569e85fdf189ad50b"
    end
  end

  # The CLI binary is `kymo` (install-name `kymostudio`, like pip/npm/cargo).
  def install
    bin.install "kymo"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/kymo --version")
  end
end
