// Mermaid renders IN-BROWSER — kroki is only the share-link warm-up path.
// Two local engines, picked per source:
//
//   - FLOWCHART (the dominant grammar, LLM output especially) renders through
//     kymostudio-core's dagre engine (mermaidToSvgDagre): kymo's OWN raster-safe
//     renderer — dagre layout + mermaid-faithful style at ~0.2% pixel-overlay vs
//     mermaid.js — reusing the core wasm already loaded for kymo diagrams (no
//     extra ~470 KB merman download).
//   - every other grammar renders through mermaid.js (~760 KB brotli), which
//     IS the reference implementation. Any core-engine error falls back here
//     too, so an unsupported syntax degrades to the slower chunk, never to a
//     broken diagram.
//
// Rules of the warm-up race (unchanged):
//   - a pristine share link has an early proxy warm-up in flight (index.html);
//     give it EARLY_WINDOW_MS to answer — an edge cache hit returns in ~300 ms
//     and costs zero extra bytes (no local engine is downloaded);
//   - a cache miss, a kroki outage, or any later render (typing) goes local:
//     no render request per keystroke, immune to kroki, works offline.
import { earlyResponse } from "./kroki";
import coreWasmUrl from "kymostudio-core/kymostudio_core_bg.wasm";
import initCore, { mermaidToSvgDagre } from "kymostudio-core";

// mermaid is pinned ~11.15 to MATCH the merman rev kymo-mermaid is built from
// (it targets mermaid@11.15): the two render paths must emit the same look.
// Bump the two together — package.json here and the rev in
// packages/rust/kymo-mermaid/Cargo.toml — never one without the other.
let mod: Promise<any> | null = null;
function loadMermaid(): Promise<any> {
  // vendor/mermaid.bundle.mjs is generated by build.sh: mermaid flattened to
  // ONE self-contained ESM file. Importing the package directly looks cleaner
  // but its per-grammar lazy-loading becomes a ~25-chunk request waterfall
  // through esbuild — measured at 5–14 s medians on Fast 4G (165 ms RTT per
  // wave). One ~760 KB brotli request beats that by an order of magnitude.
  return (mod ??= import("./vendor/mermaid.bundle.mjs").then((m: any) => {
    // `antiscript` (not `strict`) so `<br/>` in labels renders as a real line
    // break (strict HTML-encodes it → literal "<br/>"), matching mermaid.live /
    // mermaid.ai. Safe here because every render is passed through DOMPurify
    // (sanitizeSvg in kroki.ts) before it reaches the DOM — that, not mermaid's
    // securityLevel, is the XSS guard for untrusted ?s= shared source: it keeps
    // <br>/<tspan>/<foreignObject> but strips <script> and on* handlers.
    m.default.initialize({ startOnLoad: false, securityLevel: "antiscript" });
    return m.default;
  }));
}

let n = 0;
async function renderLocal(source: string): Promise<string> {
  const mermaid = await loadMermaid();
  const { svg } = await mermaid.render(`mmd-${++n}`, source);
  return svg;
}

let core: Promise<void> | null = null;
function loadCore(): Promise<void> {
  // streaming-compiled, parallel fetch; idempotent across calls. wasm-bindgen
  // wants the URL via the object form ({ module_or_path }) — the positional-arg
  // form still works but logs a deprecation warning.
  return (core ??= initCore({ module_or_path: coreWasmUrl as unknown as string }).then(() => undefined));
}

// Conservative sniff: only route sources we KNOW the slice speaks. Front-matter
// (---) and %%{init}%% directives carry config the slice ignores — let
// mermaid.js honor those.
export function isPlainFlowchart(source: string): boolean {
  for (const raw of source.split("\n")) {
    const line = raw.trim();
    if (!line) continue;
    if (line.startsWith("%%{")) return false;
    if (line.startsWith("%%")) continue;
    return /^(flowchart|graph)\b/.test(line);
  }
  return false;
}

// An edge cache hit answers well under this; a kroki cache-miss render takes
// seconds — past the window, rendering locally is the faster path.
const EARLY_WINDOW_MS = 900;

export async function renderMermaid(source: string): Promise<string> {
  const early = await Promise.race([
    earlyResponse("mermaid", source),
    new Promise<null>((resolve) => setTimeout(() => resolve(null), EARLY_WINDOW_MS)),
  ]);
  if (early && early.ok) return await early.text();
  if (isPlainFlowchart(source)) {
    try {
      await loadCore();
      return mermaidToSvgDagre(source);
    } catch {
      // unsupported syntax (or wasm failed to load) — mermaid.js takes it
    }
  }
  return renderLocal(source);
}
