#!/usr/bin/env python3
"""SVG→PNG bench — run quality + perf and render the human-readable report.

Runs the fidelity aggregator (`quality.py`) and the timing pass (`perf.py`),
writes `results/quality.json` + `results/perf.json`, and renders
`results/REPORT.md` — the side-by-side scorecard of every SVG→PNG engine against
the kymo (resvg) reference.

Run:  cd benches && uv run python svg2png/run.py [--reps N]
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import perf
import quality

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
RESULTS = HERE / "results"


def _perf_row(p: dict, key: str) -> dict | None:
    return next((r for r in p["engines"] if r["key"] == key), None)


def _render_report(q: dict, p: dict) -> str:
    env = p["environment"]
    n = q["corpus"]["items"]

    # One merged row per engine: fidelity (quality) + speed (perf).
    lines = []
    for qr in q["engines"]:
        pr = _perf_row(p, qr["key"]) or {}
        med = pr.get("per_file_median_ms")
        thr = pr.get("throughput_files_per_s")
        spd = pr.get("speed_vs_kymo")
        diff = qr["mean_abs_diff_avg"]
        pct = qr["pct_pixels_diff_avg"]
        lines.append(
            f"| {qr['label']} | `{qr['backend']}` | {qr['renders']} | "
            f"{qr['dims_match']} | "
            f"{'—' if qr['is_reference'] else (diff if diff is not None else '—')} | "
            f"{'—' if qr['is_reference'] else (str(pct) + '%' if pct is not None else '—')} | "
            f"{med if med is not None else '—'} | "
            f"{thr if thr else '—'} | "
            f"{('×' + str(spd)) if spd else '—'} | "
            f"**{qr['verdict']}** |"
        )
    table = "\n".join(lines)

    # Honesty section: every engine that failed on ≥1 file, with a sample error.
    fail_notes = []
    for qr in q["engines"]:
        if qr["failure_count"]:
            sample = qr["failures"][0]["error"] if qr["failures"] else ""
            fail_notes.append(
                f"- **{qr['label']}** failed on {qr['failure_count']}/{n} files — "
                f"e.g. `{sample}`"
            )
    fail_block = "\n".join(fail_notes) if fail_notes else "- None — every engine rendered every file."

    missing = q["missing_engines"]
    missing_block = (
        f"\n> Skipped (package not importable on this host): "
        f"{', '.join('`' + m + '`' for m in missing)}.\n"
        if missing else ""
    )

    return f"""# SVG → PNG — rasterizer scorecard

> Generated by `benches/svg2png/run.py`. **Offline bench** — re-run with
> `cd benches && uv run python svg2png/run.py` to refresh. It rasterizes a corpus
> of **real kymo SVGs** (rendered from `.kymo` sources) with every available
> Python SVG→PNG engine and scores each against the **kymo (resvg)** reference —
> the engine that authored the SVGs. *Fidelity* is deterministic; *timing* is
> machine-dependent (host below) and informational, not a gate.
{missing_block}
## Scorecard

Corpus: **{n} kymo SVGs** ({', '.join(['samples', 'conformance corpus'])}). Every
engine rasterizes the identical SVG string per item. Fidelity is measured on the
image composited over white; *diff* is mean per-channel |Δ| (0…255), *differ* is
the share of pixels off by > {q['diff_threshold']} luminance. `resvg-py` is the
control — same engine as kymo, so it should read ~0.

| Engine | Backend | Renders | Dims | Diff | Differ | Median ms | Files/s | Speed | Verdict |
|---|---|---|---|---|---|---|---|---|---|
{table}

*Diff/Differ are blank for the reference (it is compared to itself). Speed is
relative to kymo and only shown when an engine rendered the same file set, so
the ratio isn't flattered by skipping hard files.*

## What this shows

kymo emits **modern SVG**: a `<style>` block with CSS class selectors, a root
`style="max-width:100%;height:auto"`, gradient/pattern fills (`url(#…)`) and a
filter. A rasterizer has to support that CSS to reproduce the image.

- **resvg** (kymo, resvg-py) and **librsvg** (pyvips) handle it — resvg-py is
  pixel-identical to kymo (same engine), pyvips is a near-identical independent
  renderer.
- **cairosvg** rasterizes without error but drops the gradient/pattern fills
  (`url(#…)`) and the `<style>`-block class selectors, so output diverges on
  nearly every pixel — the icon-rich samples come out largely blank. Fast, but
  not faithful to this input.
- **svglib** can't parse the SVG at all (`height:auto` is not a valid ReportLab
  length), so it produces nothing.

The takeaway for kymo's own `kymo … out.png` path: resvg (shipped) and librsvg
are the faithful options; the popular pure-Python rasterizers are not, for the
SVG kymo produces.

## Per-engine failures

{fail_block}

## How it is measured

- **Corpus** — `benches/svg2png/corpus.py` renders every `samples/*.kymo` and
  `conformance/corpus/*.kymo` through the public kymo pipeline (parse → layout →
  resolve_alignments → render). Same SVG string fed to every engine.
- **Quality** — `benches/svg2png/quality.py` decodes each PNG (Pillow), composites
  over white, and compares to the kymo reference: render success, dimension
  match, mean |Δ|, and % pixels differing.
- **Performance** — `benches/svg2png/perf.py` times each engine (median of
  {env['reps']} reps per file after one warm-up); reports per-file median/p95,
  throughput, and speed vs kymo.

## Honest limitations

- **Fidelity is agreement with kymo, not absolute truth.** kymo is the system
  under test; resvg-py (same engine) reading ~0 is the method's control.
- Engines that default to a transparent background are composited over white
  before comparison, so they are not penalised for the alpha convention — only
  real drawing differences count.
- Timing is host-specific (`{env['platform']}`, Python {env['python']},
  {env['cpu_count']} CPU, reps={env['reps']}, {env['timestamp']}). Compare runs
  on the same machine.
- Scope is **Python** SVG→PNG packages. Browser engines (Chromium via Playwright,
  etc.) are the highest-fidelity reference but are out of scope here — heavy,
  and not what the `kymo` CLI ships.
"""


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--reps", type=int, default=perf.DEFAULT_REPS)
    ap.add_argument("--stamp", default=None)
    args = ap.parse_args()

    RESULTS.mkdir(parents=True, exist_ok=True)
    q = quality.collect()
    p = perf.measure(reps=args.reps, stamp=args.stamp)

    (RESULTS / "quality.json").write_text(
        json.dumps(q, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    (RESULTS / "perf.json").write_text(
        json.dumps(p, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    (RESULTS / "REPORT.md").write_text(_render_report(q, p), encoding="utf-8")

    print(f"corpus  : {q['corpus']['items']} kymo SVGs, reference '{q['reference_engine']}'")
    for qr in q["engines"]:
        pr = _perf_row(p, qr["key"]) or {}
        print(f"  {qr['label']:10} {qr['renders']:>6} render  "
              f"diff {str(qr['mean_abs_diff_avg']):>6}  "
              f"median {str(pr.get('per_file_median_ms')):>7} ms  → {qr['verdict']}")
    if q["missing_engines"]:
        print(f"missing : {', '.join(q['missing_engines'])}")
    for name in ("quality.json", "perf.json", "REPORT.md"):
        print(f"wrote   : {(RESULTS / name).relative_to(ROOT)}")


if __name__ == "__main__":
    main()
