#!/usr/bin/env python3
"""Render HomebrewFormula/kymostudio.rb from a dist release's checksums.

The `kymo` CLI ships as prebuilt binaries via cargo-dist (`dist`). This script
is the single source of truth for the Homebrew formula: it is run once by hand
to seed the initial file, and again by `.github/workflows/homebrew-formula.yml`
on every `v*` release (fed the real `sha256.sum` downloaded from the GitHub
release) to refresh the version + per-platform url/sha256, then committed to
`main`.

Why a separate formula instead of dist's built-in `homebrew` installer: that
installer publishes to a dedicated `homebrew-<name>` tap repo; we deliberately
host the formula in this repo under HomebrewFormula/ (tapped by URL), so we
render and commit it ourselves. See dist-workspace.toml for the rationale.

Usage:
    render_homebrew_formula.py --tag v0.4.5 --checksums sha256.sum \
        --out HomebrewFormula/kymostudio.rb

`--checksums` is a `sha256sum`-format file (one `<hex>  <filename>` per line),
i.e. dist's unified `sha256.sum` release asset. Targets with no matching line
fall back to a 64-zero placeholder so the seed file stays valid Ruby before any
dist release exists.
"""

from __future__ import annotations

import argparse
import sys

REPO = "kymostudio/kymostudio"
PLACEHOLDER = "0" * 64

# dist target triple -> (Homebrew OS block, Homebrew arch block). The tarball
# name is always `kymostudio-<triple>.tar.xz` (flat: `kymo` at the archive root).
TARGETS = [
    ("aarch64-apple-darwin", "on_macos", "on_arm"),
    ("x86_64-apple-darwin", "on_macos", "on_intel"),
    ("aarch64-unknown-linux-gnu", "on_linux", "on_arm"),
    ("x86_64-unknown-linux-gnu", "on_linux", "on_intel"),
]


def parse_checksums(path: str | None) -> dict[str, str]:
    """Parse a `sha256sum`-format file into {filename: hex}."""
    sums: dict[str, str] = {}
    if not path:
        return sums
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split()
            if len(parts) < 2:
                continue
            digest, name = parts[0], parts[-1]
            # sha256sum marks binary mode with a leading '*' on the filename.
            sums[name.lstrip("*")] = digest
    return sums


def render(tag: str, sums: dict[str, str]) -> str:
    version = tag[1:] if tag.startswith("v") else tag

    def block(os_name: str) -> str:
        rows = []
        for triple, os_blk, arch_blk in TARGETS:
            if os_blk != os_name:
                continue
            tarball = f"kymostudio-{triple}.tar.xz"
            url = f"https://github.com/{REPO}/releases/download/{tag}/{tarball}"
            sha = sums.get(tarball, PLACEHOLDER)
            rows.append(
                f"    {arch_blk} do\n"
                f'      url "{url}"\n'
                f'      sha256 "{sha}"\n'
                f"    end"
            )
        return "\n".join(rows)

    return f"""\
# This file is auto-generated by scripts/render_homebrew_formula.py and
# refreshed on every release by .github/workflows/homebrew-formula.yml.
# Do not edit by hand — changes will be overwritten on the next release.
class Kymostudio < Formula
  desc "Render SVG diagrams to PNG and PDF (pure-Rust, no system deps)"
  homepage "https://github.com/{REPO}"
  version "{version}"
  license "Apache-2.0"

  on_macos do
{block("on_macos")}
  end

  on_linux do
{block("on_linux")}
  end

  # The CLI binary is `kymo` (install-name `kymostudio`, like pip/npm/cargo).
  def install
    bin.install "kymo"
  end

  test do
    assert_match version.to_s, shell_output("#{{bin}}/kymo --version")
  end
end
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--tag", required=True, help="Release tag, e.g. v0.4.5")
    ap.add_argument("--checksums", help="sha256sum-format file (dist sha256.sum)")
    ap.add_argument("--out", required=True, help="Output .rb path")
    args = ap.parse_args()

    sums = parse_checksums(args.checksums)
    content = render(args.tag, sums)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(content)

    missing = [
        f"kymostudio-{t}.tar.xz"
        for t, _, _ in TARGETS
        if f"kymostudio-{t}.tar.xz" not in sums
    ]
    if missing:
        print(
            f"warning: placeholder sha256 for: {', '.join(missing)}",
            file=sys.stderr,
        )
    print(f"wrote {args.out} (version {args.tag})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
